include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

rule:
  prefer_const_constructors: true
  prefer_const_literals_to_create_immutables: true
  prefer_const_declarations: true
